# Business problem understanding

* Based on the given car features, predict the selling price of the used car
* Required R2 should be 0.85 on train and test data

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter('ignore')

**Loading the data**

In [2]:
df=pd.read_excel('cars_data.xlsx')

# Data Understanding

In [3]:
df.head()

,Name,Price,Rating,city,Kilometers,Year_of_Purchase,Owner,Fuel_Type,Transmission,RTO,Insurance,Insurance_Type
0,2010 Maruti Alto LXI,"₹ 174,699",4out of 5,3686,"Kilometers34,854 km",Year of PurchaseMay 2010,OwnerFirst Owner,FuelPetrol,TransmissionMANUAL,RTOAP09,NaN,Insurance TypeInsurance Expired
1,2013 Maruti Wagon R 1.0 VXI,"₹ 333,999",4.2out of 5,3686,"Kilometers39,541 km",Year of PurchaseJuly 2013,OwnerSecond Owner,FuelPetrol,TransmissionMANUAL,RTOAP28,Insurance6/8/2021,Insurance TypeComp
2,2014 Maruti Wagon R 1.0 VXI,"₹ 353,199",4.3out of 5,3686,"Kilometers23,233 km",Year of PurchaseMarch 2014,OwnerSecond Owner,FuelPetrol,TransmissionMANUAL,RTOAP28,Insurance28/4/2021,Insurance TypeComp
3,2013 Hyundai Eon D LITE PLUS,"₹ 237,899",4.4out of 5,3686,"Kilometers27,748 km",Year of PurchaseNovember 2013,OwnerFirst Owner,FuelPetrol,TransmissionMANUAL,RTOAP13,Insurance1/1/2022,Insurance TypeComp
4,2017 Hyundai Eon ERA PLUS,"₹ 300,699",4.4out of 5,3686,"Kilometers12,238 km",Year of PurchaseAugust 2017,OwnerSecond Owner,FuelPetrol,TransmissionMANUAL,RTOTS10,NaN,Insurance TypeExpired

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32158 entries, 0 to 32157
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              32158 non-null  object
 1   Price             32158 non-null  object
 2   Rating            32158 non-null  object
 3   city              32158 non-null  int64
 4   Kilometers        32158 non-null  object
 5   Year_of_Purchase  32158 non-null  object
 6   Owner             32158 non-null  object
 7   Fuel_Type         32158 non-null  object
 8   Transmission      29342 non-null  object
 9   RTO               32158 non-null  object
 10  Insurance         22965 non-null  object
 11  Insurance_Type    32158 non-null  object
dtypes: int64(1), object(11)
memory usage: 2.9+ MB

In [5]:
df.columns.tolist()

['Name',
 'Price',
 'Rating',
 'city',
 'Kilometers',
 'Year_of_Purchase',
 'Owner',
 'Fuel_Type',
 'Transmission',
 'RTO',
 'Insurance',
 'Insurance_Type']

In [6]:
df.Name.nunique()

6885

In [7]:
df.Price.nunique()

4822

In [8]:
df.city.unique()

array([3686, 5732, 4709,  777, 2423, 2378,  290, 1692, 2130,  769],
      dtype=int64)

In [9]:
df.Kilometers.nunique()

29089

In [10]:
df.Owner.unique()

array(['OwnerFirst Owner', 'OwnerSecond Owner', 'OwnerThird Owner',
       'OwnerFourth Owner', 'OwnerSixth Owner', 'OwnerFifth Owner',
       'OwnerEighth Owner', 'OwnerSeventh Owner', 'OwnerNinth Owner',
       'OwnerTenth Owner'], dtype=object)

In [11]:
df.Fuel_Type.unique()

array(['FuelPetrol', 'FuelDiesel', 'FuelPetrol + LPG', 'FuelPetrol + CNG',
       'FuelElectric', 'FuelHybrid'], dtype=object)

In [12]:
df.Transmission.unique()

array(['TransmissionMANUAL', nan, 'TransmissionAUTOMATIC'], dtype=object)

In [13]:
df.Insurance.nunique()

921

In [14]:
df.RTO.unique()

array(['RTOAP09', 'RTOAP28', 'RTOAP13', 'RTOTS10', 'RTOAP11', 'RTOTS07',
       'RTOAP10', 'RTOTS11', 'RTOTS13', 'RTOTS08', 'RTOTS09', 'RTOAP29',
       'RTOTS15', 'RTOTS12', 'RTODL5C', 'RTOAP31', 'RTOAP23', 'RTODL10',
       'RTOTN51', 'RTOAP16', 'RTOAP12', 'RTOAP07', 'RTOMH04', 'RTOHR29',
       'RTOUP16', 'RTOKA05', 'RTOKA03', 'RTODL8C', 'RTOKA01', 'RTOAP27',
       'RTOUP32', 'RTOAP36', 'RTOMH06', 'RTOWB02', 'RTOTS03', 'RTODL4C',
       'RTOKL03', 'RTOAP22', 'RTOAP20', 'RTOMH19', 'RTOTS29', 'RTOOD02',
       'RTOAP15', 'RTORJ02', 'RTOAP05', 'RTOHR51', 'RTOAP39', 'RTOUP15',
       'RTORJ14', 'RTOKA09', 'RTOTS34', 'RTOHR26', 'RTOTS04', 'RTOTN01',
       'RTOKA51', 'RTOTN09', 'RTOMH02', 'RTOAP02', 'RTOMH03', 'RTOTS16',
       'RTOJH01', 'RTOAP04', 'RTOTS05', 'RTOUP14', 'RTOUP80', 'RTOMH31',
       'RTOTS35', 'RTOKA41', 'RTOAHO1', 'RTOAP35', 'RTOWB26', 'RTOAP37',
       'RTODL3C', 'RTOOR05', 'RTOKA04', 'RTOUP65', 'RTOCH01', 'RTODL12',
       'RTOTS36', 'RTOAP25', 'RTOTN14', 'RTOTN38', 'RTOKA53', 'RTOTS32',
       'RTOGJ12', 'RTOMH43', 'RTOMH01', 'RTOTN05', 'RTOTS17', 'RTODL1C',
       'RTODL2C', 'RTOOD11', 'RTOWB06', 'RTOUK08', 'RTOUP53', 'RTOTS23',
       'RTOAP24', 'RTORJ27', 'RTOAPO9', 'RTOMH20', 'RTOTS02', 'RTOTS01',
       'RTOAP26', 'RTOTS28', 'RTODL9C', 'RTOTN12', 'RTOAP01', 'RTOHR55',
       'RTOHR05', 'RTOKA35', 'RTOMP08', 'RTOTN07', 'RTOAP03', 'RTOPB08',
       'RTOAP21', 'RTOAP1F', 'RTOTS06', 'RTOMH12', 'RTOCH03', 'RTOMH34',
       'RTORJ19', 'RTOMP04', 'RTOKL33', 'RTOWB12', 'RTOMH15', 'RTOUP25',
       'RTOGJ05', 'RTOHR70', 'RTOPB65', 'RTOMJF1', 'RTOPB10', 'RTOAP32',
       'RTOTS33', 'RTOPY01', 'RTOAP33', 'RTOOR19', 'RTOCG13', 'RTOGJ5C',
       'RTOTS25', 'RTOAS04', 'RTOGJ21', 'RTOTS20', 'RTOKA02', 'RTOTS22',
       'RTO0R14', 'RTOAP5R', 'RTOKA52', 'RTOKL32', 'RTOTS0C', 'RTOJH04',
       'RTODL6C', 'RTOTN10', 'RTOTS30', 'RTOUP78', 'RTOGJ18', 'RTOHR21',
       'RTOTS21', 'RTOTS1O', 'RTOKA38', 'RTOTS27', 'RTOKA36', 'RTOTS31',
       'RTOHR10', 'RTOPB03', 'RTOUP70', 'RTOMH14', 'RTOMH13', 'RTOGJ03',
       'RTOTN19', 'RTOCG04', 'RTOMH47', 'RTOKL01', 'RTOKA32', 'RTOPB35',
       'RTOKA50', 'RTOMH05', 'RTOMH24', 'RTOTS19', 'RTOGJ01', 'RTOTE09',
       'RTOMP09', 'RTOTN11', 'RTOPB02', 'RTOKA28', 'RTOAP9A', 'RTOTS0E',
       'RTOTN72', 'RTODL07', 'RTOMH26', 'RTOPB09', 'RTOJH05', 'RTOTN28',
       'RTOHP64', 'RTOUP20', 'RTOWD02', 'RTOUP83', 'RTOOR15', 'RTOGJ06',
       'RTOCH04', 'RTOOR14', 'RTOTN22', 'RTOCG18', 'RTOTS26', 'RTOHR72',
       'RTOPB11', 'RTOWB40', 'RTOMH32', 'RTOTD13', 'RTOTS18', 'RTOHR61',
       'RTODLCA', 'RTOTN02', 'RTOAP30', 'RTOKL25', 'RTOKA34', 'RTOOD15',
       'RTOTN45', 'RTOUP21', 'RTOWB20', 'RTOTN13', 'RTOTN06', 'RTOTN20',
       'RTOTN04', 'RTOTN73', 'RTOTN18', 'RTOTN21', 'RTOTN68', 'RTOTN85',
       'RTOKL04', 'RTOTN03', 'RTOTN25', 'RTOTN31', 'RTOTN49', 'RTOTN47',
       'RTOTN23', 'RTOTN66', 'RTOTN37', 'RTOTN24', 'RTOKL46', 'RTOPY05',
       'RTOTN55', 'RTOUP33', 'RTOKL45', 'RTOTN63', 'RTOTN87', 'RTOKL11',
       'RTODL13', 'RTOTSL5', 'RTOTN58', 'RTOTN52', 'RTOAN01', 'RTODL7C',
       'RTOTN61', 'RTOTN70', 'RTOTN29', 'RTOKL49', 'RTOCAZ5', 'RTOTN67',
       'RTOTN32', 'RTOTN59', 'RTOTN33', 'RTOKL24', 'RTOTN15', 'RTOJH10',
       'RTOTN27', 'RTOTN91', 'RTOKL42', 'RTOKL63', 'RTOTN48', 'RTOTN30',
       'RTOTN16', 'RTOTN36', 'RTOTN65', 'RTOTNO7', 'RTOGJ3B', 'RTOTN81',
       'RTOTN50', 'RTOTN64', 'RTOTN42', 'RTOTN69', 'RTOPY02', 'RTOKL22',
       'RTOTN74', 'RTOMH09', 'RTOTN97', 'RTOTN99', 'RTOTN82', 'RTOTN76',
       'RTOTN43', 'RTOTN39', 'RTOTN41', 'RTOTN46', 'RTOTN57', 'RTOKL39',
       'RTOKA19', 'RTOKA25', 'RTOKA20', 'RTOKA44', 'RTOKA16', 'RTOUP38',
       'RTOKA22', 'RTOPB29', 'RTORJ16', 'RTOKA24', 'RTOBR01', 'RTOUK06',
       'RTOUP93', 'RTOAS23', 'RTOKA27', 'RTOKA26', 'RTOKA06', 'RTOMP12',
       'RTOKA07', 'RTOKA29', 'RTOKA14', 'RTOKA08', 'RTOKL51', 'RTOWB22',
       'RTOKL09', 'RTOKA42', 'RTOMP19', 'RTOKA13', 'RTOWB18', 'RTOMP05',
       'RTOKA17', 'RTOTN83', 'RTOUP11', 'RTOKA43', 'RTOUK07', 'RTOHR27',
       'RTOGJ10', 'RTOMH11', 'RTOKA30', 'RTOKL07', 'RTOBR21', 'RTOKA18',
       'RTOKA63', 'RTOKA40', 'RTOKL05', 'RTOKA37', 'RTOKA11', 'RTOAS01',
       'RTOUK05', 'RTOPB23', 'RTOBR2N', 'RTOMH48', 'RTOCAN8', 'RTOOR02',
       'RTOKA15', 'RTOML05', 'RTOKA31', 'RTOHR07', 'RTOUP52', 'RTOKL02',
       'RTOHP15', 'RTOK02M', 'RTOMP10', 'RTOTN54', 'RTOWB44', 'RTOKA12',
       'RTOHR30', 'RTOKA67', 'RTOKL13', 'RTOKA33', 'RTOJH09', 'RTOKA54',
       'RTOKa03', 'RTOKA55', 'RTOHR16', 'RTODL02', 'RTOMP20', 'RTOKL56',
       'RTORJ20', 'RTOKL59', 'RTOUK04', 'RTOKL58', 'RTOKL47', 'RTOKL27',
       'RTOKA21', 'RTOKA48', 'RTOUP82', 'RTOUP62', 'RTOGJ02', 'RTOKA59',
       'RTOHR01', 'RTOGA05', 'RTOKL43', 'RTOGA06', 'RTOKA64', 'RTOHR06',
       'RTOKL23', 'RTOKL57', 'RTOGA08', 'RTOKL14', 'RTOKL75', 'RTOCKR5',
       'RTOKS03', 'RTOHR24', 'RTOCAZ6', 'RTOKA46', 'RTOHR18', 'RTOMH46',
       'RTOHR60', 'RTOHP88', 'RTOJK02', 'RTOTN77', 'RTOTN40', 'RTOKL08',
       'RTOMH49', 'RTOCKQ2', 'RTOGJ38', 'RTOKA23', 'RTOKA66', 'RTOKL12',
       'RTOHP39', 'RTOHR81', 'RTOKL60', 'RTOKA65', 'RTOHR20', 'RTOHR03',
       'RTOKA56', 'RTOKL65', 'RTOKL17', 'RTOKA10', 'RTORJ32', 'RTOKA5M',
       'RTOKA47', 'RTOKA39', 'RTOGJ15', 'RTOCKW1', 'RTOKL18', 'RTOWB08',
       'RTOWB24', 'RTOWB42', 'RTOWB10', 'RTOWB98', 'RTOWB74', 'RTOWB28',
       'RTOWB96', 'RTOWB34', 'RTOWN06', 'RTOWB16', 'RTOPB36', 'RTOCG16',
       'RTOWB90', 'RTOWB38', 'RTOOD04', 'RTOWB14', 'RTOWB54', 'RTOCG07',
       'RTOGA03', 'RTOWE02', 'RTOWB30', 'RTOTR01', 'RTOGJ23', 'RTOCG10',
       'RTOWB52', 'RTOCG12', 'RTOOD09', 'RTOWB8C', 'RTOWMF5', 'RTOWB77',
       'RTOOR07', 'RTOHP62', 'RTOBR10', 'RTOMP15', 'RTOWB36', 'RTOGJ27',
       'RTOBR14', 'RTOWB66', 'RTOJH22', 'RTOWB58', 'RTOBR42', 'RTO0D02',
       'RTOPB06', 'RTORJ40', 'RTOOD19', 'RTOMH08', 'RTOMH30', 'RTOHR34',
       'RTOUP96', 'RTODL14', 'RTOMH10', 'RTOMH18', 'RTOMP22', 'RTOMH16',
       'RTOUK01', 'RTOMH42', 'RTOMH39', 'RTOKL53', 'RTOMH21', 'RTOMH40',
       'RTOGA07', 'RTOHP17', 'RTOMH17', 'RTOBR06', 'RTOHP38', 'RTOUK15',
       'RTOJH12', 'RTOMH41', 'RTOMH25', 'RTOMH2P', 'RTODD03', 'RTOJH15',
       'RTOOD33', 'RTOMH38', 'RTOMH45', 'RTOMH27', 'RTOJH02', 'RTOHR02',
       'RTORJ45', 'RTOMH07', 'RTOKL30', 'RTOHR13', 'RTOMH44', 'RTODL11',
       'RTOMP07', 'RTOGJ04', 'RTOMH50', 'RTOMH28', 'RTOPB05', 'RTOPB39',
       'RTOGJ1A', 'RTOMH29', 'RTOMH23', 'RTOMH22', 'RTOBR1U', 'RTOMP38',
       'RTOGA01', 'RTOKL31', 'RTOHR12', 'RTORJ17', 'RTOMP13', 'RTOMG02',
       'RTORJ22', 'RTODL2F', 'RTODN09', 'RTOUA08', 'RTOHR17', 'RTOGJ37',
       'RTOGJ16', 'RTOGJ1H', 'RTOAS03', 'RTOUP07', 'RTOKL10', 'RTOGJ26',
       'RTOJH07', 'RTORJ07', 'RTOPB46', 'RTOAS07', 'RTOUP47', 'RTOUP42',
       'RTOAS24', 'RTOUP40', 'RTOUP72', 'RTOUP44', 'RTOUP34', 'RTOUP76',
       'RTOUP43', 'RTOUP30', 'RTOUP51', 'RTOUP92', 'RTOUP27', 'RTOUP64',
       'RTORJ01', 'RTOGJ2A', 'RTOUP74', 'RTOUA12', 'RTOUP81', 'RTOUP54',
       'RTOUP41', 'RTOUP85', 'RTOJH24', 'RTOUP60', 'RTOUP55', 'RTOBR17',
       'RTOUP13', 'RTOUP50', 'RTOUP71', 'RTOUAG3', 'RTOBR28', 'RTORJ30',
       'RTOUP35', 'RTOUP45', 'RTOUP84', 'RTOUA07', 'RTOMP28', 'RTOUP17',
       'RTOUP90', 'RTOUP31', 'RTOUP77', 'RTOUP63', 'RTOUP57', 'RTOGJ17',
       'RTOUP86', 'RTOUP66', 'RTOUP61', 'RTOUP36', 'RTOAS25', 'RTOHP47',
       'RTOUMR7', 'RTOGJ1K', 'RTOMH35', 'RTOGJ13', 'RTOGJ31', 'RTOGJ07',
       'RTOGH01', 'RTOGJ33', 'RTOGJ08', 'RTOGJ14', 'RTOGJ24', 'RTORJ04',
       'RTOGJ09', 'RTOGJ36', 'RTOGJ11', 'RTOGK01', 'RTOGJ20', 'RTORJ39',
       'RTOGJ25', 'RTORJ29', 'RTOGJ9M', 'RTOGUD4', 'RTOGJ3C', 'RTOGJ35',
       'RTOUP23', 'RTOGJ0H', 'RTOGJ22', 'RTOGJ19', 'RTOUA06', 'RTORJ38',
       'RTOAS06', 'RTOHR36', 'RTORJ06', 'RTOGJ6D', 'RTORJ03', 'RTOMP44',
       'RTOPB13', 'RTOHR42', 'RTOBR1S', 'RTORJ26', 'RTORJ05', 'RTORJ41',
       'RTORJ28', 'RTORJ23', 'RTORJ25', 'RTORJ15', 'RTORJ13', 'RTORJ18',
       'RTORJ37', 'RTORJ47', 'RTORJ48', 'RTORJ09', 'RTOMP41', 'RTORJ34',
       'RTORJ33', 'RTORJ10', 'RTODL08', 'RTORJ36', 'RTOOD18', 'RTOUP75',
       'RTORJ21', 'RTOAR01', 'RTOMP06', 'RTORJ12', 'RTORJ11', 'RTORJ44',
       'RTORJ08', 'RTOMP17', 'RTOHR22', 'RTORJ49', 'RTORJ51', 'RTORJ42',
       'RTOHR35', 'RTORJ24', 'RTORJ52', 'RTOUP79', 'RTOHR66', 'RTORJ31',
       'RTOHR44', 'RTOPB12', 'RTOCh01', 'RTOHR49', 'RTOPB16', 'RTOHP31',
       'RTOHR78', 'RTOHR85', 'RTOHR71', 'RTOPB04', 'RTOHR04', 'RTOPB53',
       'RTOHP81', 'RTOHP91', 'RTOHR08', 'RTOPB70', 'RTOPB74', 'RTOHP23',
       'RTOPB07', 'RTOPB61', 'RTOHP30', 'RTOHR11', 'RTOHP52', 'RTOHR32',
       'RTOHR59', 'RTOPB27', 'RTOHP16', 'RTOPB22', 'RTOHR54', 'RTOHP12',
       'RTOPB32', 'RTOPB31', 'RTOHR14', 'RTOHR52', 'RTOHR80', 'RTOHP93',
       'RTOHR41', 'RTOHR19', 'RTOHP33', 'RTOPB34', 'RTOHP86', 'RTOCG11',
       'RTOHR40', 'RTOHP82', 'RTOPB51', 'RTOPB59', 'RTOHP63', 'RTOHP68',
       'RTOHR68', 'RTOHR09', 'RTODLCZ', 'RTOPB71', 'RTOHP10', 'RTOHP55',
       'RTOHR31', 'RTOPB30', 'RTOMN07', 'RTOHR92', 'RTOHR82', 'RTOHR91',
       'RTOPB48', 'RTOHR76', 'RTOPB87', 'RTOHP72', 'RTOHP20', 'RTOHP19',
       'RTOPB19', 'RTOHP03', 'RTOPB15', 'RTOHP22', 'RTOJK01', 'RTOHR15',
       'RTOPB55', 'RTOHP74', 'RTOPB72', 'RTOHP09', 'RTOPB69', 'RTOPB25',
       'RTOHR45', 'RTOHR77', 'RTOHR46', 'RTOHR50', 'RTOPB37', 'RTOHR23',
       'RTOHP40', 'RTOPB20', 'RTOHP07', 'RTOPCP7', 'RTOHP69', 'RTOPB18',
       'RTOPB57', 'RTOHP57', 'RTOHR33', 'RTOHR37', 'RTOPB88', 'RTOHR79',
       'RTOHP37', 'RTOHP25', 'RTOHP97'], dtype=object)

In [15]:
df.Insurance_Type.unique()

array(['Insurance TypeInsurance Expired', 'Insurance TypeComp',
       'Insurance TypeExpired', 'Insurance TypeThird_party',
       'Insurance TypeZero_Dep', 'Insurance TypeNA',
       'Insurance TypeZero Depreciation', 'Insurance Type3rd Party',
       'Insurance TypeComprehensive', 'Insurance Typenull',
       'Insurance TypeNot Available', 'Insurance TypeNormal'],
      dtype=object)

In [16]:
df.isnull().sum()

Name                   0
Price                  0
Rating                 0
city                   0
Kilometers             0
Year_of_Purchase       0
Owner                  0
Fuel_Type              0
Transmission        2816
RTO                    0
Insurance           9193
Insurance_Type         0
dtype: int64

# Data Preprocessing

In [17]:
df['Price'].unique()

array(['₹ 174,699', '₹ 333,999', '₹ 353,199', ..., '₹ 1,094,733',
       '₹ 496,000', '₹ 96,500'], dtype=object)

**o/p variable**

In [18]:
df['Price'] = df['Price'].str.replace('₹ ','')
df['Price'] = df['Price'].str.replace(',','')
df['Price'] = df.Price.str.replace(' ','')
df['Price'] = df.Price.astype('int')

**i/p variable**

In [19]:
df['Brand'] = df['Name'].str.extract(r'\d{4}\s(\w+)')
df['Model'] = df['Name'].str.extract(r'\d{4}\s\w+\s(\w+)')

In [20]:
df['Name'].nunique()

6885

In [21]:
df['Rate'] = df['Rating'].str.extract(r'(\d+\.?\d*)').astype(float)

In [22]:
df['Kilometers']=df['Kilometers'].str.replace(',','')
df['Kms']=df['Kilometers'].str.extract(r'(\d+\.?\d*)').astype(int)

In [23]:
df['years_old']=df['Year_of_Purchase'].str.extract(r'(\d+\.?\d*)').astype(int)

In [24]:
df['Fuel_Type']=df['Fuel_Type'].str.replace('+','and')

In [25]:
# Extracting the 2-letter RTO code (after 'RTO' and before digits)
df['RTO_state_code'] = df['RTO'].str.extract(r'RTO([A-Z]{2})\d+')

In [26]:
df['years_old']=2024-df['years_old']

In [27]:
df=df.drop(columns=['Name','RTO','Insurance','Rating','Kilometers','Year_of_Purchase'],axis=1)

city = transform
kms = Log Transform
rate = same
years_old = same

---owner = Ordinal Encoding
fuel_type = dummy
transmission= label
RTO_state_code = One-Hot Encoding
insurance_type=labelencoding/dummy
brand = One-Hot/label if>15
Model = nominal
varient = ordinal

# Encoding

In [28]:
df['Owner'].unique()

array(['OwnerFirst Owner', 'OwnerSecond Owner', 'OwnerThird Owner',
       'OwnerFourth Owner', 'OwnerSixth Owner', 'OwnerFifth Owner',
       'OwnerEighth Owner', 'OwnerSeventh Owner', 'OwnerNinth Owner',
       'OwnerTenth Owner'], dtype=object)

In [29]:
owner_mapping = {"OwnerFirst Owner": 1, "OwnerSecond Owner": 2, "OwnerThird Owner": 3, 'OwnerFourth Owner':4, 'OwnerFifth Owner':5, 'OwnerSixth Owner': 6, 'OwnerSeventh Owner':7, 'OwnerEighth Owner': 8, 'OwnerNinth Owner': 9,'OwnerTenth Owner':10}
df["Owner"] = df["Owner"].map(owner_mapping).astype('int')

In [30]:
df.Transmission.unique()

array(['TransmissionMANUAL', nan, 'TransmissionAUTOMATIC'], dtype=object)

In [31]:
df['Transmission'] = df.groupby('Brand')['Transmission'].transform(
    lambda x: x.fillna(x.mode()[0]) if not x.mode().empty else x.fillna('Unknown')
)

In [32]:
df['Transmission'] = df['Transmission'].map({'TransmissionMANUAL': 0, 'TransmissionAUTOMATIC': 1, 'Unknown':2})

In [33]:
df['Insurance_Type'] = (df['Insurance_Type'] == 'Comprehensive').astype(int)

In [34]:
brand_mean_price = df.groupby('Brand')['Price'].mean().to_dict()
df['Brand'] = df['Brand'].map(brand_mean_price)

In [35]:
model_mean_price = df.groupby('Model')['Price'].mean().to_dict()
df['Model'] = df['Model'].map(model_mean_price)

In [36]:
df['RTO_state_code'].fillna('Unknown', inplace=True)

In [37]:
rto_mean_price = df.groupby('RTO_state_code')['Price'].mean().to_dict()
df['RTO_state_code'] = df['RTO_state_code'].map(rto_mean_price)

In [38]:
from sklearn.preprocessing import LabelEncoder
df['Fuel_Type'] = LabelEncoder().fit_transform(df['Fuel_Type'])

In [39]:
df.head()

,Price,city,Owner,Fuel_Type,Transmission,Insurance_Type,Brand,Model,Rate,Kms,years_old,RTO_state_code
0,174699,3686,1,3,0,0,372393.056151,202491.449115,4.0,34854,14,329544.263393
1,333999,3686,2,3,0,0,372393.056151,238634.672269,4.2,39541,11,329544.263393
2,353199,3686,2,3,0,0,372393.056151,238634.672269,4.3,23233,10,329544.263393
3,237899,3686,1,3,0,0,417222.792187,243570.041667,4.4,27748,11,329544.263393
4,300699,3686,2,3,0,0,417222.792187,243570.041667,4.4,12238,7,700334.102554

In [40]:
continous=['Price','city','Kms','Brand','RTO_state_code','Model']

In [41]:
df[continous].skew()

Price             4.516217
city              0.219366
Kms               2.291942
Brand             3.890219
RTO_state_code    1.489587
Model             2.712197
dtype: float64

In [42]:
from scipy.stats import boxcox
df['Price'],params=boxcox(df['Price'])

In [43]:
df['Brand'],params=boxcox(df['Brand'])
df['RTO_state_code'],params=boxcox(df['RTO_state_code'])
df['Model'],params=boxcox(df['Model'])

In [47]:
df.isnull().sum()

Price             0
city              0
Owner             0
Fuel_Type         0
Transmission      0
Insurance_Type    0
Brand             0
Model             0
Rate              0
Kms               0
years_old         0
RTO_state_code    0
dtype: int64

In [50]:
df.duplicated().sum()

0

In [52]:
x=df.drop('Price',axis=1)
y=df['Price']

In [54]:
r2_Train=[]
cv=[]
for i in range(0,100):
    from sklearn.model_selection import train_test_split
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=i)
    
    from sklearn.linear_model import LinearRegression
    model=LinearRegression()
    model.fit(x_train,y_train)
    
    ypred_train=model.predict(x_train)
    
    from sklearn.metrics import r2_score
    r2_Train.append(r2_score(y_train,ypred_train))
    from sklearn.model_selection import cross_val_score
    cv.append(cross_val_score(model,x_train,y_train,cv=5).mean())
    
em=pd.DataFrame({"r2_Train":r2_Train,'cv':cv})
gm=em[(abs(em['r2_Train']-em['cv'])<0.05)] # for values
rs=gm[gm['cv']==gm['cv'].max()].index[0]
print("best random state number:",rs)

best random state number: 45

In [51]:
df.to_csv('cleaned_data',index=False)